-- 1 Total de participantes por evento
-- Relações: 5 (TB_EVENTO, RL_ATIVIDADE_EVENTO, TB_ATIVIDADE, RL_PARTICIPANTE_ATIVIDADE, TB_PARTICIPANTE)
-- Comandos: JOIN, GROUP BY, COUNT
SELECT 
    e.ID_EVENTO,
    e.DS_LOCAL,
    COUNT(DISTINCT p.CD_CPF_PARTICIPANTE) AS QT_PARTICIPANTES
FROM TB_EVENTO e
JOIN RL_ATIVIDADE_EVENTO rae ON rae.ID_EVENTO = e.ID_EVENTO
JOIN TB_ATIVIDADE a ON a.ID_ATIVIDADE = rae.ID_ATIVIDADE
JOIN RL_PARTICIPANTE_ATIVIDADE rpa ON rpa.ID_ATIVIDADE = a.ID_ATIVIDADE
JOIN TB_PARTICIPANTE p ON p.CD_CPF_PARTICIPANTE = rpa.CD_CPF_PARTICIPANTE
GROUP BY e.ID_EVENTO, e.DS_LOCAL;

-- 2 Valor médio de pagamento por evento e categoria
-- Relações: 6 (EVENTO, RL_ATIVIDADE_EVENTO, ATIVIDADE, RL_PARTICIPANTE_ATIVIDADE, PARTICIPANTE, PAGAMENTO)
-- Comandos: JOIN, GROUP BY, COUNT, AVG
SELECT 
    e.ID_EVENTO,
    e.DS_LOCAL,
    p.TP_CATEGORIA,
    ROUND(AVG(pg.VL_PAGAMENTO), 2) AS VL_MEDIO
FROM TB_EVENTO e
JOIN RL_ATIVIDADE_EVENTO rae ON e.ID_EVENTO = rae.ID_EVENTO
JOIN TB_ATIVIDADE a ON a.ID_ATIVIDADE = rae.ID_ATIVIDADE
JOIN RL_PARTICIPANTE_ATIVIDADE rpa ON rpa.ID_ATIVIDADE = a.ID_ATIVIDADE
JOIN TB_PARTICIPANTE p ON p.CD_CPF_PARTICIPANTE = rpa.CD_CPF_PARTICIPANTE
JOIN TB_PAGAMENTO pg ON pg.ID_INSCRICAO = p.ID_INSCRICAO
GROUP BY e.ID_EVENTO, e.DS_LOCAL, p.TP_CATEGORIA;

-- 3 Evento(s) com o maior número de atividades
-- Relações: 3 (EVENTO, RL_ATIVIDADE_EVENTO, ATIVIDADE)
-- Comandos: JOIN, GROUP BY, COUNT, SUBCONSULTA
SELECT 
    e.DS_LOCAL,
    COUNT(rae.ID_ATIVIDADE) AS QTD_ATIVIDADES
FROM TB_EVENTO e
JOIN RL_ATIVIDADE_EVENTO rae ON e.ID_EVENTO = rae.ID_EVENTO
JOIN TB_ATIVIDADE a ON a.ID_ATIVIDADE = rae.ID_ATIVIDADE
GROUP BY e.DS_LOCAL
HAVING COUNT(rae.ID_ATIVIDADE) >= ALL (
    SELECT COUNT(ID_ATIVIDADE)
    FROM RL_ATIVIDADE_EVENTO
    GROUP BY ID_EVENTO
);

-- 4 Participantes com pagamento acima da média da própria categoria
-- Relações: 4 (PARTICIPANTE, PAGAMENTO, subconsulta PARTICIPANTE + PAGAMENTO)
-- Comandos: JOIN, SUBCONSULTA, GROUP BY (implícito em AVG)
SELECT 
    P1.DS_NOME,
    P1.TP_CATEGORIA,
    PG1.VL_PAGAMENTO
FROM TB_PARTICIPANTE P1
JOIN TB_PAGAMENTO PG1 ON P1.ID_INSCRICAO = PG1.ID_INSCRICAO
WHERE PG1.VL_PAGAMENTO > (
    SELECT AVG(PG2.VL_PAGAMENTO)
    FROM TB_PAGAMENTO PG2
    JOIN TB_PARTICIPANTE P2 ON PG2.ID_INSCRICAO = P2.ID_INSCRICAO
    WHERE P2.TP_CATEGORIA = P1.TP_CATEGORIA
);

-- 5 Participantes com mais de uma atividade e que pagaram
-- Relações: 3 (PARTICIPANTE, RL_PARTICIPANTE_ATIVIDADE, PAGAMENTO)
-- Comandos: JOIN, GROUP BY, COUNT, HAVING
SELECT 
    p.DS_NOME,
    COUNT(rpa.ID_ATIVIDADE) AS QTD_ATIVIDADES,
    SUM(pg.VL_PAGAMENTO) AS TOTAL_PAGO
FROM TB_PARTICIPANTE p
JOIN RL_PARTICIPANTE_ATIVIDADE rpa ON p.CD_CPF_PARTICIPANTE = rpa.CD_CPF_PARTICIPANTE
JOIN TB_PAGAMENTO pg ON pg.ID_INSCRICAO = p.ID_INSCRICAO
GROUP BY p.DS_NOME
HAVING COUNT(rpa.ID_ATIVIDADE) > 1;

-- 6 Artigos e seus eventos (comparação elemento a elemento ANY)
-- Relações: 5 (ARTIGO, RL_ARTIGO_ATIVIDADE, ATIVIDADE, RL_ATIVIDADE_EVENTO, EVENTO)
-- Comandos: JOIN, GROUP BY, COUNT, ANY
SELECT 
    a.ID_ARTIGO,
    a.DS_TITULO,
    e.DS_LOCAL AS LOCAL_EVENTO,
    COUNT(DISTINCT atv.ID_ATIVIDADE) AS QT_ATIVIDADES
FROM TB_ARTIGO a
JOIN RL_ARTIGO_ATIVIDADE raa ON raa.ID_ARTIGO = a.ID_ARTIGO
JOIN TB_ATIVIDADE atv ON atv.ID_ATIVIDADE = raa.ID_ATIVIDADE
JOIN RL_ATIVIDADE_EVENTO rae ON rae.ID_ATIVIDADE = atv.ID_ATIVIDADE
JOIN TB_EVENTO e ON e.ID_EVENTO = rae.ID_EVENTO
WHERE e.ID_EVENTO = ANY (
    SELECT ID_EVENTO
    FROM RL_ATIVIDADE_EVENTO
)
GROUP BY a.ID_ARTIGO, a.DS_TITULO, e.DS_LOCAL;

-- 7 Pagamentos acima da média geral e maiores que qualquer da categoria 2
-- Relações: 4 (PARTICIPANTE, PAGAMENTO, subconsulta PARTICIPANTE + PAGAMENTO)
-- Comandos: JOIN, SUBCONSULTA, ANY
SELECT 
    p.DS_NOME,
    pg.VL_PAGAMENTO
FROM TB_PARTICIPANTE p
JOIN TB_PAGAMENTO pg ON p.ID_INSCRICAO = pg.ID_INSCRICAO
WHERE pg.VL_PAGAMENTO > (
    SELECT AVG(VL_PAGAMENTO) FROM TB_PAGAMENTO
)
AND pg.VL_PAGAMENTO > ANY (
    SELECT PG2.VL_PAGAMENTO
    FROM TB_PAGAMENTO PG2
    JOIN TB_PARTICIPANTE P2 ON PG2.ID_INSCRICAO = P2.ID_INSCRICAO
    WHERE P2.TP_CATEGORIA = 2
);

-- 8 Ranking de pagamentos por categoria
-- Relações: 3 (PARTICIPANTE, PAGAMENTO, INSCRICAO)
-- Comandos: JOIN, WINDOW (RANK), GROUP BY
SELECT 
    p.TP_CATEGORIA,
    p.DS_NOME,
    pg.VL_PAGAMENTO,
    RANK() OVER (PARTITION BY p.TP_CATEGORIA ORDER BY pg.VL_PAGAMENTO DESC) AS POSICAO
FROM TB_PARTICIPANTE p
JOIN TB_PAGAMENTO pg ON p.ID_INSCRICAO = pg.ID_INSCRICAO
JOIN TB_INSCRICAO i ON i.ID_INSCRICAO = p.ID_INSCRICAO;

-- 9 Eventos com média de pagamento maior que a média geral
-- Relações: 6 (EVENTO, RL_ATIVIDADE_EVENTO, ATIVIDADE, RL_PARTICIPANTE_ATIVIDADE, PARTICIPANTE, PAGAMENTO)
-- Comandos: JOIN, GROUP BY, COUNT, SUBCONSULTA
SELECT 
    e.ID_EVENTO,
    e.DS_LOCAL,
    ROUND(AVG(pg.VL_PAGAMENTO), 2) AS MEDIA_EVENTO
FROM TB_EVENTO e
JOIN RL_ATIVIDADE_EVENTO rae ON e.ID_EVENTO = rae.ID_EVENTO
JOIN TB_ATIVIDADE a ON a.ID_ATIVIDADE = rae.ID_ATIVIDADE
JOIN RL_PARTICIPANTE_ATIVIDADE rpa ON rpa.ID_ATIVIDADE = a.ID_ATIVIDADE
JOIN TB_PARTICIPANTE p ON p.CD_CPF_PARTICIPANTE = rpa.CD_CPF_PARTICIPANTE
JOIN TB_PAGAMENTO pg ON pg.ID_INSCRICAO = p.ID_INSCRICAO
GROUP BY e.ID_EVENTO, e.DS_LOCAL
HAVING AVG(pg.VL_PAGAMENTO) > (
    SELECT AVG(VL_PAGAMENTO) FROM TB_PAGAMENTO
);

-- 10 Diferença de pagamento e média da categoria
-- Relações: 3 (PARTICIPANTE, PAGAMENTO, INSCRICAO)
-- Comandos: JOIN, WINDOW (AVG OVER), GROUP BY
SELECT 
    p.DS_NOME,
    p.TP_CATEGORIA,
    pg.VL_PAGAMENTO,
    pg.VL_PAGAMENTO - AVG(pg.VL_PAGAMENTO) OVER (PARTITION BY p.TP_CATEGORIA) AS DIFERENCA_MEDIA
FROM TB_PARTICIPANTE p
JOIN TB_PAGAMENTO pg ON p.ID_INSCRICAO = pg.ID_INSCRICAO
JOIN TB_INSCRICAO i ON i.ID_INSCRICAO = p.ID_INSCRICAO;

-- 11 Total de artigos por evento
-- Relações: 4 (EVENTO, RL_ATIVIDADE_EVENTO, RL_ARTIGO_ATIVIDADE, ARTIGO)
-- Comandos: JOIN, GROUP BY, COUNT
SELECT 
    e.DS_LOCAL,
    COUNT(a.ID_ARTIGO) AS TOTAL_ARTIGOS
FROM TB_EVENTO e
JOIN RL_ATIVIDADE_EVENTO rae ON rae.ID_EVENTO = e.ID_EVENTO
JOIN RL_ARTIGO_ATIVIDADE raa ON raa.ID_ATIVIDADE = rae.ID_ATIVIDADE
JOIN TB_ARTIGO a ON a.ID_ARTIGO = raa.ID_ARTIGO
GROUP BY e.DS_LOCAL;

-- 12 Participantes com maior valor pago 
-- Relações: 3 (PARTICIPANTE, PAGAMENTO, INSCRICAO)
-- Comandos: JOIN, SUBCONSULTA, GROUP BY
SELECT 
    p.DS_NOME,
    pg.VL_PAGAMENTO
FROM TB_PARTICIPANTE p
JOIN TB_PAGAMENTO pg ON p.ID_INSCRICAO = pg.ID_INSCRICAO
JOIN TB_INSCRICAO i ON i.ID_INSCRICAO = p.ID_INSCRICAO
WHERE pg.VL_PAGAMENTO >= ALL (
    SELECT VL_PAGAMENTO FROM TB_PAGAMENTO
);

-- 13 Participantes e quantidade de atividades por evento
-- Relações: 5 (PARTICIPANTE, RL_PARTICIPANTE_ATIVIDADE, ATIVIDADE, RL_ATIVIDADE_EVENTO, EVENTO)
-- Comandos: JOIN, GROUP BY, COUNT
SELECT 
    e.ID_EVENTO,
    e.DS_LOCAL,
    p.DS_NOME,
    COUNT(a.ID_ATIVIDADE) AS QTD_ATIVIDADES
FROM TB_EVENTO e
JOIN RL_ATIVIDADE_EVENTO rae ON e.ID_EVENTO = rae.ID_EVENTO
JOIN TB_ATIVIDADE a ON a.ID_ATIVIDADE = rae.ID_ATIVIDADE
JOIN RL_PARTICIPANTE_ATIVIDADE rpa ON rpa.ID_ATIVIDADE = a.ID_ATIVIDADE
JOIN TB_PARTICIPANTE p ON p.CD_CPF_PARTICIPANTE = rpa.CD_CPF_PARTICIPANTE
GROUP BY e.ID_EVENTO, e.DS_LOCAL, p.DS_NOME;

-- 14 Total pago por evento
-- Relações: 6 (EVENTO, RL_ATIVIDADE_EVENTO, ATIVIDADE, RL_PARTICIPANTE_ATIVIDADE, PARTICIPANTE, PAGAMENTO)
-- Comandos: JOIN, GROUP BY, COUNT, SUM
SELECT 
    e.DS_LOCAL,
    SUM(pg.VL_PAGAMENTO) AS TOTAL_PAGO
FROM TB_EVENTO e
JOIN RL_ATIVIDADE_EVENTO rae ON e.ID_EVENTO = rae.ID_EVENTO
JOIN TB_ATIVIDADE a ON a.ID_ATIVIDADE = rae.ID_ATIVIDADE
JOIN RL_PARTICIPANTE_ATIVIDADE rpa ON rpa.ID_ATIVIDADE = a.ID_ATIVIDADE
JOIN TB_PARTICIPANTE p ON p.CD_CPF_PARTICIPANTE = rpa.CD_CPF_PARTICIPANTE
JOIN TB_PAGAMENTO pg ON pg.ID_INSCRICAO = p.ID_INSCRICAO
GROUP BY e.DS_LOCAL;

-- 15 Percentual de participantes que efetuaram pagamento 
-- Relações: 3 (PARTICIPANTE, INSCRICAO, PAGAMENTO)
-- Comandos: JOIN, COUNT, SUBCONSULTA
SELECT 
    ROUND(
        (SELECT COUNT(DISTINCT p1.CD_CPF_PARTICIPANTE)
         FROM TB_PARTICIPANTE p1
         JOIN TB_PAGAMENTO pg1 ON pg1.ID_INSCRICAO = p1.ID_INSCRICAO) * 100.0 /
        COUNT(*), 2
    ) AS PERCENTUAL_PAGANTES
FROM TB_PARTICIPANTE p
JOIN TB_INSCRICAO i ON i.ID_INSCRICAO = p.ID_INSCRICAO;

-- 16 Eventos com artigos e participantes (duas subconsultas EXISTS)
-- Relações: 5 (EVENTO, subconsulta 1 com RL_ATIVIDADE_EVENTO + RL_ARTIGO_ATIVIDADE, subconsulta 2 com RL_ATIVIDADE_EVENTO + RL_PARTICIPANTE_ATIVIDADE)
-- Comandos: SUBCONSULTA, EXISTS, COUNT
SELECT 
    e.DS_LOCAL,
    e.DT_EVENTO
FROM TB_EVENTO e
WHERE EXISTS (
    SELECT 1 FROM RL_ATIVIDADE_EVENTO rae
    JOIN RL_ARTIGO_ATIVIDADE raa ON rae.ID_ATIVIDADE = raa.ID_ATIVIDADE
    WHERE rae.ID_EVENTO = e.ID_EVENTO
)
AND EXISTS (
    SELECT 1 FROM RL_ATIVIDADE_EVENTO rae
    JOIN RL_PARTICIPANTE_ATIVIDADE rpa ON rae.ID_ATIVIDADE = rpa.ID_ATIVIDADE
    WHERE rae.ID_EVENTO = e.ID_EVENTO
);

-- 17 Participantes com pagamento abaixo da média da categoria
-- Relações: 4 (PARTICIPANTE, PAGAMENTO, subconsulta PARTICIPANTE + PAGAMENTO)
-- Comandos: JOIN, SUBCONSULTA, GROUP BY
SELECT 
    P1.DS_NOME,
    P1.TP_CATEGORIA,
    PG1.VL_PAGAMENTO
FROM TB_PARTICIPANTE P1
JOIN TB_PAGAMENTO PG1 ON P1.ID_INSCRICAO = PG1.ID_INSCRICAO
WHERE PG1.VL_PAGAMENTO < (
    SELECT AVG(PG2.VL_PAGAMENTO)
    FROM TB_PAGAMENTO PG2
    JOIN TB_PARTICIPANTE P2 ON PG2.ID_INSCRICAO = P2.ID_INSCRICAO
    WHERE P2.TP_CATEGORIA = P1.TP_CATEGORIA
);

-- 18 Valor médio e máximo de pagamento por evento
-- Relações: 6 (EVENTO, RL_ATIVIDADE_EVENTO, ATIVIDADE, RL_PARTICIPANTE_ATIVIDADE, PARTICIPANTE, PAGAMENTO)
-- Comandos: JOIN, GROUP BY, COUNT, MAX, AVG
SELECT 
    e.DS_LOCAL,
    ROUND(AVG(pg.VL_PAGAMENTO), 2) AS MEDIA,
    MAX(pg.VL_PAGAMENTO) AS MAXIMO
FROM TB_EVENTO e
JOIN RL_ATIVIDADE_EVENTO rae ON e.ID_EVENTO = rae.ID_EVENTO
JOIN TB_ATIVIDADE a ON a.ID_ATIVIDADE = rae.ID_ATIVIDADE
JOIN RL_PARTICIPANTE_ATIVIDADE rpa ON rpa.ID_ATIVIDADE = a.ID_ATIVIDADE
JOIN TB_PARTICIPANTE p ON p.CD_CPF_PARTICIPANTE = rpa.CD_CPF_PARTICIPANTE
JOIN TB_PAGAMENTO pg ON pg.ID_INSCRICAO = p.ID_INSCRICAO
GROUP BY e.DS_LOCAL;

-- 19 Artigos em eventos com mais de duas atividades
-- Relações: 4 (ARTIGO, RL_ARTIGO_ATIVIDADE, RL_ATIVIDADE_EVENTO, EVENTO)
-- Comandos: JOIN, GROUP BY, COUNT, SUBCONSULTA
SELECT 
    a.DS_TITULO,
    e.DS_LOCAL
FROM TB_ARTIGO a
JOIN RL_ARTIGO_ATIVIDADE raa ON a.ID_ARTIGO = raa.ID_ARTIGO
JOIN RL_ATIVIDADE_EVENTO rae ON raa.ID_ATIVIDADE = rae.ID_ATIVIDADE
JOIN TB_EVENTO e ON e.ID_EVENTO = rae.ID_EVENTO
WHERE e.ID_EVENTO IN (
    SELECT ID_EVENTO
    FROM RL_ATIVIDADE_EVENTO
    GROUP BY ID_EVENTO
    HAVING COUNT(ID_ATIVIDADE) > 2
)
GROUP BY a.DS_TITULO, e.DS_LOCAL;

-- 20 Participantes com pagamento igual à média geral (refeito com 3+ tabelas)
-- Relações: 3 (PARTICIPANTE, PAGAMENTO, INSCRICAO)
-- Comandos: JOIN, SUBCONSULTA, GROUP BY
SELECT 
    p.DS_NOME,
    pg.VL_PAGAMENTO
FROM TB_PARTICIPANTE p
JOIN TB_PAGAMENTO pg ON p.ID_INSCRICAO = pg.ID_INSCRICAO
JOIN TB_INSCRICAO i ON i.ID_INSCRICAO = p.ID_INSCRICAO
WHERE pg.VL_PAGAMENTO = (
    SELECT ROUND(AVG(VL_PAGAMENTO), 2)
    FROM TB_PAGAMENTO
);
