-- Materialized View 
-- 1. Quantas pessoas se inscreveram em *cada* atividade específica.
-- 2. Quanto dinheiro aquela atividade gerou (soma dos pagamentos dos inscritos nela).
-- 3. Onde e quando ela ocorreu.
CREATE MATERIALIZED VIEW MV_METRICAS_OPERACIONAIS_ATIVIDADE AS
SELECT
    A.ID_ATIVIDADE,
    E.ID_EVENTO,
    A.TP_CATEGORIA AS CAT_ATIVIDADE,
    E.DT_EVENTO,
    COUNT(RPA.CD_CPF_PARTICIPANTE) AS QT_INSCRITOS,
    COALESCE(SUM(P.VL_PAGAMENTO), 0) AS VL_RECEITA_ASSOCIADA
FROM
    TB_ATIVIDADE A
    INNER JOIN RL_ATIVIDADE_EVENTO RAE ON A.ID_ATIVIDADE = RAE.ID_ATIVIDADE
    INNER JOIN TB_EVENTO E ON RAE.ID_EVENTO = E.ID_EVENTO
    LEFT JOIN RL_PARTICIPANTE_ATIVIDADE RPA ON A.ID_ATIVIDADE = RPA.ID_ATIVIDADE
    LEFT JOIN TB_PARTICIPANTE PART ON RPA.CD_CPF_PARTICIPANTE = PART.CD_CPF_PARTICIPANTE
    LEFT JOIN TB_PAGAMENTO P ON PART.ID_INSCRICAO = P.ID_INSCRICAO
GROUP BY
    A.ID_ATIVIDADE, E.ID_EVENTO, A.TP_CATEGORIA, E.DT_EVENTO;

-- Grafico 1 (consulta intermediária): Mostrar quais atividades específicas trazem mais retorno financeiro.
SELECT
    A.DS_NOME_ATIVIDADE,
    E.DS_LOCAL,
    M.VL_RECEITA_ASSOCIADA
FROM
    MV_METRICAS_OPERACIONAIS_ATIVIDADE M
    INNER JOIN TB_ATIVIDADE A ON M.ID_ATIVIDADE = A.ID_ATIVIDADE
    INNER JOIN TB_EVENTO E ON M.ID_EVENTO = E.ID_EVENTO
WHERE
    M.VL_RECEITA_ASSOCIADA > 0
ORDER BY
    M.VL_RECEITA_ASSOCIADA DESC
LIMIT 5;

-- Grafico 2 (consulta intermediária): Mostrar qual local demanda mais estrutura física (baseado no volume de inscrições, não apenas pessoas únicas).
SELECT
    E.DS_LOCAL,
    SUM(M.QT_INSCRITOS) AS TOTAL_INSCRICOES,
    ROUND(SUM(M.QT_INSCRITOS) * 100.0 / (SELECT SUM(QT_INSCRITOS) FROM MV_METRICAS_OPERACIONAIS_ATIVIDADE), 2) AS PCT_DO_TOTAL
FROM
    MV_METRICAS_OPERACIONAIS_ATIVIDADE M
    INNER JOIN TB_EVENTO E ON M.ID_EVENTO = E.ID_EVENTO
    INNER JOIN TB_ATIVIDADE A ON M.ID_ATIVIDADE = A.ID_ATIVIDADE 
GROUP BY
    E.DS_LOCAL;

-- Grafico 3 (consulta intermediária): Analise de tendencia mensal
SELECT
    TO_CHAR(M.DT_EVENTO, 'YYYY-MM') AS MES_ANO,
    E.DS_LOCAL,
    SUM(M.QT_INSCRITOS) AS TOTAL_INSCRITOS_MES
FROM
    MV_METRICAS_OPERACIONAIS_ATIVIDADE M
    INNER JOIN TB_EVENTO E ON M.ID_EVENTO = E.ID_EVENTO
    INNER JOIN TB_ATIVIDADE A ON M.ID_ATIVIDADE = A.ID_ATIVIDADE
GROUP BY
    TO_CHAR(M.DT_EVENTO, 'YYYY-MM'),
    E.DS_LOCAL
ORDER BY
    MES_ANO ASC;

-- Grafico 4 (consulta intermediária): Saber se atividades "Workshop" enchem mais que atividades "Palestras", na média.
SELECT
    A.TP_CATEGORIA,
    ROUND(AVG(M.QT_INSCRITOS), 2) AS MEDIA_INSCRITOS_POR_ATIVIDADE,
    COUNT(DISTINCT E.ID_EVENTO) AS QTD_EVENTOS_ENVOLVIDOS
FROM
    MV_METRICAS_OPERACIONAIS_ATIVIDADE M
    INNER JOIN TB_ATIVIDADE A ON M.ID_ATIVIDADE = A.ID_ATIVIDADE
    INNER JOIN TB_EVENTO E ON M.ID_EVENTO = E.ID_EVENTO
GROUP BY
    A.TP_CATEGORIA
HAVING 
    AVG(M.QT_INSCRITOS) > 0;

-- Grafico 5 (consulta avançada): Comparar a receita de apenas uma atividade contra a média de um evento.
SELECT
    A.DS_NOME_ATIVIDADE,
    E.DS_LOCAL,
    M.VL_RECEITA_ASSOCIADA,
    AVG(M.VL_RECEITA_ASSOCIADA) OVER (PARTITION BY M.ID_EVENTO) AS MEDIA_RECEITA_EVENTO,
    (M.VL_RECEITA_ASSOCIADA - AVG(M.VL_RECEITA_ASSOCIADA) OVER (PARTITION BY M.ID_EVENTO)) AS DIFERENCA_DA_MEDIA
FROM
    MV_METRICAS_OPERACIONAIS_ATIVIDADE M
    INNER JOIN TB_ATIVIDADE A ON M.ID_ATIVIDADE = A.ID_ATIVIDADE
    INNER JOIN TB_EVENTO E ON M.ID_EVENTO = E.ID_EVENTO
WHERE
    M.QT_INSCRITOS > 5
ORDER BY
    DIFERENCA_DA_MEDIA DESC;

-- Grafico 6 (consulta avançada): Criar um ranking top 3 das atividades mais populares dentro de cada tipo.
SELECT 
    RANKING.NOME_ATIVIDADE,
    RANKING.CATEGORIA,
    RANKING.INSCRITOS,
    RANKING.POSICAO
FROM (
    SELECT
        A.DS_NOME_ATIVIDADE AS NOME_ATIVIDADE,
        A.TP_CATEGORIA AS CATEGORIA,
        M.QT_INSCRITOS AS INSCRITOS,
        DENSE_RANK() OVER (PARTITION BY A.TP_CATEGORIA ORDER BY M.QT_INSCRITOS DESC) AS POSICAO
    FROM
        MV_METRICAS_OPERACIONAIS_ATIVIDADE M
        INNER JOIN TB_ATIVIDADE A ON M.ID_ATIVIDADE = A.ID_ATIVIDADE
        INNER JOIN TB_EVENTO E ON M.ID_EVENTO = E.ID_EVENTO
) AS RANKING
WHERE 
    RANKING.POSICAO <= 3
ORDER BY 
    RANKING.CATEGORIA, RANKING.POSICAO;
