CREATE TABLE TB_EVENTO (
    ID_EVENTO INT NOT NULL,
    DT_EVENTO DATE NOT NULL,
    DS_LOCAL VARCHAR(255) NOT NULL,
    CONSTRAINT PK_EVENTO PRIMARY KEY (ID_EVENTO)
);

CREATE TABLE TB_INSCRICAO (
    ID_INSCRICAO INT NOT NULL, 
    CONSTRAINT PK_INSCRICAO PRIMARY KEY (ID_INSCRICAO) 
);

CREATE TABLE TB_PARTICIPANTE (
    CD_CPF_PARTICIPANTE CHAR(11) NOT NULL, 
    DS_NOME VARCHAR(150) NOT NULL, 
    DS_EMAIL VARCHAR(100) NOT NULL, 
    TP_CATEGORIA INT NOT NULL, 
    ID_INSCRICAO INT NOT NULL, 

    CONSTRAINT PK_PARTICIPANTE PRIMARY KEY (CD_CPF_PARTICIPANTE), 
    CONSTRAINT UK_PARTICIPANTE_EMAIL UNIQUE (DS_EMAIL),           
    CONSTRAINT FK_PARTICIPANTE_INSCRICAO FOREIGN KEY (ID_INSCRICAO) REFERENCES TB_INSCRICAO (ID_INSCRICAO), 

    CONSTRAINT CK_CPF_FORMATO CHECK (CD_CPF_PARTICIPANTE ~ '^[0-9]{11}$')
);

CREATE TABLE TB_ARTIGO (
    ID_ARTIGO INT NOT NULL,
    DS_TITULO VARCHAR(250) NOT NULL,
    DS_RESUMO VARCHAR(4000),        
    DS_PATH_DOCUMENTO VARCHAR(500), 
    CONSTRAINT PK_ARTIGO PRIMARY KEY (ID_ARTIGO) 
);

CREATE TABLE TB_PAGAMENTO (
    ID_PAGAMENTO INT NOT NULL,
    CD_BOLETO VARCHAR(100) NOT NULL, 
    DT_PAGAMENTO DATE,               
    VL_PAGAMENTO NUMERIC(10, 2) NOT NULL,
    ID_INSCRICAO INT NOT NULL,    
    CONSTRAINT PK_PAGAMENTO PRIMARY KEY (ID_PAGAMENTO), 
    CONSTRAINT UK_PAGAMENTO_BOLETO UNIQUE (CD_BOLETO), 
    CONSTRAINT FK_PAGAMENTO_INSCRICAO FOREIGN KEY (ID_INSCRICAO) REFERENCES TB_INSCRICAO (ID_INSCRICAO)
);

CREATE TABLE TB_ATIVIDADE (
    ID_ATIVIDADE INT NOT NULL,
    DS_NOME_ATIVIDADE VARCHAR(200) NOT NULL, 
    TP_CATEGORIA INT,                     
    CONSTRAINT PK_ATIVIDADE PRIMARY KEY (ID_ATIVIDADE) 
);

CREATE TABLE RL_ARTIGO_ATIVIDADE (
    ID_ARTIGO INT NOT NULL,   
    ID_ATIVIDADE INT NOT NULL, 
    CONSTRAINT PK_ARTIGO_ATIVIDADE PRIMARY KEY (ID_ARTIGO, ID_ATIVIDADE), 
    CONSTRAINT FK_RL_ARTIGO FOREIGN KEY (ID_ARTIGO) REFERENCES TB_ARTIGO (ID_ARTIGO), 
    CONSTRAINT FK_RL_ATIVIDADE FOREIGN KEY (ID_ATIVIDADE) REFERENCES TB_ATIVIDADE (ID_ATIVIDADE) 
);

CREATE TABLE RL_PARTICIPANTE_ATIVIDADE (
    CD_CPF_PARTICIPANTE CHAR(11) NOT NULL, 
    ID_ATIVIDADE INT NOT NULL,        
    CONSTRAINT PK_PARTICIPANTE_ATIVIDADE PRIMARY KEY (CD_CPF_PARTICIPANTE, ID_ATIVIDADE),
    CONSTRAINT FK_RL_PARTICIPANTE FOREIGN KEY (CD_CPF_PARTICIPANTE) REFERENCES TB_PARTICIPANTE (CD_CPF_PARTICIPANTE),
    CONSTRAINT FK_RL_ATIVIDADE_PART FOREIGN KEY (ID_ATIVIDADE) REFERENCES TB_ATIVIDADE (ID_ATIVIDADE)
);

CREATE TABLE RL_ATIVIDADE_EVENTO (
    ID_ATIVIDADE INT NOT NULL, 
    ID_EVENTO INT NOT NULL,  
    CONSTRAINT PK_ATIVIDADE_EVENTO PRIMARY KEY (ID_ATIVIDADE, ID_EVENTO),
    CONSTRAINT FK_RL_ATIVIDADE_EVT FOREIGN KEY (ID_ATIVIDADE) REFERENCES TB_ATIVIDADE (ID_ATIVIDADE),
    CONSTRAINT FK_RL_EVENTO_ATIV FOREIGN KEY (ID_EVENTO) REFERENCES TB_EVENTO (ID_EVENTO)
);