CREATE INDEX IDX_PARTICIPANTE_ID_INSCRICAO ON TB_PARTICIPANTE (ID_INSCRICAO);

CREATE INDEX IDX_PAGAMENTO_ID_INSCRICAO ON TB_PAGAMENTO (ID_INSCRICAO);

CREATE INDEX IDX_PAGAMENTO_DT_PAGAMENTO ON TB_PAGAMENTO (DT_PAGAMENTO);

CREATE INDEX IDX_PARTICIPANTE_TP_CATEGORIA ON TB_PARTICIPANTE (TP_CATEGORIA);

CREATE INDEX IDX_EVENTO_DT_EVENTO ON TB_EVENTO (DT_EVENTO);



CREATE INDEX IDX_RL_PART_ATIV_ID_ATIVIDADE ON RL_PARTICIPANTE_ATIVIDADE (ID_ATIVIDADE);

CREATE INDEX IDX_RL_ATIV_EVT_ID_EVENTO ON RL_ATIVIDADE_EVENTO (ID_EVENTO);

CREATE INDEX IDX_RL_ART_ATIV_ID_ATIVIDADE ON RL_ARTIGO_ATIVIDADE (ID_ATIVIDADE);

CREATE INDEX IDX_PARTICIPANTE_DS_NOME ON TB_PARTICIPANTE (DS_NOME);

CREATE INDEX IDX_ARTIGO_DS_TITULO ON TB_ARTIGO (DS_TITULO);