EXPLAIN ANALYZE
SELECT
    A.TP_CATEGORIA,
    COUNT(P.CD_CPF_PARTICIPANTE) AS total_participantes
FROM
    TB_PARTICIPANTE AS P
JOIN
    RL_PARTICIPANTE_ATIVIDADE AS PA ON P.CD_CPF_PARTICIPANTE = PA.CD_CPF_PARTICIPANTE
JOIN
    TB_ATIVIDADE AS A ON PA.ID_ATIVIDADE = A.ID_ATIVIDADE
GROUP BY
    A.TP_CATEGORIA;

explain analyse
SELECT
    E.DS_LOCAL,
    P.TP_CATEGORIA,
    COUNT(DISTINCT P.CD_CPF_PARTICIPANTE) AS total_participantes
FROM
    TB_EVENTO AS E
JOIN
    RL_ATIVIDADE_EVENTO AS AE ON E.ID_EVENTO = AE.ID_EVENTO
JOIN
    RL_PARTICIPANTE_ATIVIDADE AS PA ON AE.ID_ATIVIDADE = PA.ID_ATIVIDADE
JOIN
    TB_PARTICIPANTE AS P ON PA.CD_CPF_PARTICIPANTE = P.CD_CPF_PARTICIPANTE
GROUP BY
    E.ID_EVENTO, E.DS_LOCAL, P.TP_CATEGORIA
ORDER BY
    E.DS_LOCAL, P.TP_CATEGORIA;

explain analyse
SELECT
    P.TP_CATEGORIA,
    COUNT(PG.ID_PAGAMENTO) AS numero_de_pagamentos
FROM
    TB_PAGAMENTO AS PG
JOIN
    TB_INSCRICAO AS I ON PG.ID_INSCRICAO = I.ID_INSCRICAO
JOIN
    TB_PARTICIPANTE AS P ON I.ID_INSCRICAO = P.ID_INSCRICAO
GROUP BY
    P.TP_CATEGORIA;

explain analyse
SELECT
    P.DS_NOME,
    COUNT(PA.ID_ATIVIDADE) AS total_atividades,
    DENSE_RANK() OVER(ORDER BY COUNT(PA.ID_ATIVIDADE) DESC) AS ranking_participacao
FROM
    TB_PARTICIPANTE AS P
JOIN
    RL_PARTICIPANTE_ATIVIDADE AS PA ON P.CD_CPF_PARTICIPANTE = PA.CD_CPF_PARTICIPANTE
JOIN
    TB_ATIVIDADE AS A ON PA.ID_ATIVIDADE = A.ID_ATIVIDADE
GROUP BY
    P.CD_CPF_PARTICIPANTE, P.DS_NOME;

explain analyse
SELECT
    A.DS_NOME_ATIVIDADE,
    COUNT(PA.CD_CPF_PARTICIPANTE) AS num_participantes
FROM
    TB_ATIVIDADE AS A
JOIN
    RL_ATIVIDADE_EVENTO AS AE ON A.ID_ATIVIDADE = AE.ID_ATIVIDADE
JOIN
    RL_PARTICIPANTE_ATIVIDADE AS PA ON A.ID_ATIVIDADE = PA.ID_ATIVIDADE
WHERE
    AE.ID_EVENTO = 1
GROUP BY
    A.ID_ATIVIDADE, A.DS_NOME_ATIVIDADE
ORDER BY
    num_participantes DESC;

SELECT
    P.DS_NOME,
    P.DS_EMAIL,
    COUNT(RPA.ID_ATIVIDADE) AS QTD_ATIVIDADES
FROM
    TB_PARTICIPANTE AS P
JOIN
    RL_PARTICIPANTE_ATIVIDADE AS RPA ON P.CD_CPF_PARTICIPANTE = RPA.CD_CPF_PARTICIPANTE
JOIN
    TB_ATIVIDADE AS A ON RPA.ID_ATIVIDADE = A.ID_ATIVIDADE
GROUP BY
    P.CD_CPF_PARTICIPANTE, P.DS_NOME, P.DS_EMAIL
HAVING
    COUNT(RPA.ID_ATIVIDADE) > 1
ORDER BY
    QTD_ATIVIDADES DESC;

SELECT
    PG.DT_PAGAMENTO,
    COUNT(PG.ID_PAGAMENTO) AS NUM_PAGAMENTOS_DIA,
    SUM(PG.VL_PAGAMENTO) AS TOTAL_DIA,
    SUM(SUM(PG.VL_PAGAMENTO)) OVER (ORDER BY PG.DT_PAGAMENTO) AS SOMA_CUMULATIVA
FROM
    TB_PAGAMENTO AS PG
JOIN
    TB_INSCRICAO AS I ON PG.ID_INSCRICAO = I.ID_INSCRICAO
JOIN
    TB_PARTICIPANTE AS P ON I.ID_INSCRICAO = P.ID_INSCRICAO
WHERE
    PG.DT_PAGAMENTO IS NOT NULL
GROUP BY
    PG.DT_PAGAMENTO
ORDER BY
    PG.DT_PAGAMENTO;

WITH PagamentosParticipante AS (
    SELECT
        P.DS_NOME,
        P.TP_CATEGORIA,
        PG.VL_PAGAMENTO,
        PG.ID_PAGAMENTO
    FROM
        TB_PARTICIPANTE AS P
    JOIN
        TB_INSCRICAO AS I ON P.ID_INSCRICAO = I.ID_INSCRICAO
    JOIN
        TB_PAGAMENTO AS PG ON I.ID_INSCRICAO = PG.ID_INSCRICAO
    WHERE
        PG.DT_PAGAMENTO IS NOT NULL
)
SELECT
    DS_NOME,
    TP_CATEGORIA,
    VL_PAGAMENTO,
    RANK() OVER (PARTITION BY TP_CATEGORIA ORDER BY VL_PAGAMENTO DESC) AS RANK_NA_CATEGORIA
FROM
    PagamentosParticipante;

SELECT
    E.DS_LOCAL AS EVENTO,
    A.TP_CATEGORIA AS TIPO_ATIVIDADE,
    COUNT(A.ID_ATIVIDADE) AS TOTAL_ATIVIDADES
FROM
    TB_EVENTO AS E
JOIN
    RL_ATIVIDADE_EVENTO AS RAE ON E.ID_EVENTO = RAE.ID_EVENTO
JOIN
    TB_ATIVIDADE AS A ON RAE.ID_ATIVIDADE = A.ID_ATIVIDADE
GROUP BY
    E.ID_EVENTO, E.DS_LOCAL, A.TP_CATEGORIA
ORDER BY
    EVENTO, TOTAL_ATIVIDADES DESC;

SELECT
    P.DS_NOME,
    P.DS_EMAIL,
    COUNT(RPA.ID_ATIVIDADE) AS QTD_ATIVIDADES_INSCRITAS
FROM
    TB_PARTICIPANTE AS P
JOIN
    RL_PARTICIPANTE_ATIVIDADE AS RPA ON P.CD_CPF_PARTICIPANTE = RPA.CD_CPF_PARTICIPANTE
JOIN
    TB_INSCRICAO AS I ON P.ID_INSCRICAO = I.ID_INSCRICAO
LEFT JOIN
    TB_PAGAMENTO AS PG ON I.ID_INSCRICAO = PG.ID_INSCRICAO AND PG.DT_PAGAMENTO IS NOT NULL
WHERE
    PG.ID_PAGAMENTO IS NULL
GROUP BY
    P.CD_CPF_PARTICIPANTE, P.DS_NOME, P.DS_EMAIL;

